version: '3.4'

services:
  app:
    image:  ${DOCKER_REGISTRY}orderswebapi
    build:
      context: .
      dockerfile: EntityFrameworkSQLite/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32034:80"
    volumes:
      - .\EntityFrameworkSQLite:/src/EntityFrameworkSQLite
    restart: always
